version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile # Assuming the Dockerfile is in the same directory
    image: backend:latest # Set your desired image name and tag here
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - shop_db_data:/var/lib/postgresql/data

volumes:
  shop_db_data: