# Generated by Django 4.1.3 on 2022-12-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_campaign_discount'),
        ('customer', '0005_alter_bascet_color_alter_bascet_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Wish',
        ),
    ]
