# Generated by Django 4.1.3 on 2022-12-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_campaign_discount'),
        ('customer', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bascet',
            new_name='BascetItem',
        ),
    ]
