# Generated by Django 4.1.3 on 2022-12-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_coupon_alter_bascetitem_options_purchase_ordercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='used_customers',
            field=models.ManyToManyField(blank=True, to='customer.customer'),
        ),
    ]
