# Generated by Django 4.1.3 on 2022-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='b', max_length=50),
            preserve_default=False,
        ),
    ]
