# Generated by Django 4.1.3 on 2022-12-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_order_total_price_purchase_all_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='all_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
