# Generated by Django 4.1.3 on 2022-12-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_purchase_all_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='used_customers',
            field=models.ManyToManyField(blank=True, related_name='used_coupons', to='customer.customer'),
        ),
    ]
