# Generated by Django 4.1.3 on 2023-01-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
