# Generated by Django 4.1.3 on 2023-01-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_passwordreset_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
