# Generated by Django 4.1.3 on 2022-12-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_campaign_category_created_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='campaigns',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='ecommerce.campaign'),
        ),
    ]
