# Generated by Django 4.1.3 on 2022-12-12 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_product_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
