# Generated by Django 4.1.3 on 2022-12-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slide',
            field=models.BooleanField(default=False),
        ),
    ]
