# Generated by Django 4.1.3 on 2022-12-12 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_campaign_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='discount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
