# Generated by Django 4.1.3 on 2022-12-28 07:49

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_campaign_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=100),
        ),
        TrigramExtension()
    ]
