# Generated by Django 4.1.3 on 2023-01-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_rename_title_product_title_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
